#!/usr/bin/env python3
"""Auto-refresh YouTube cookies using Playwright"""

import asyncio
import os
import sys
from playwright.async_api import async_playwright


async def refresh_youtube_cookies():
    email = os.getenv('YOUTUBE_EMAIL')
    password = os.getenv('YOUTUBE_PASSWORD')
    
    if not email or not password:
        print("ERROR: YOUTUBE_EMAIL or YOUTUBE_PASSWORD not set")
        return False
    
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=['--disable-blink-features=AutomationControlled']
        )
        context = await browser.new_context(
            viewport={'width': 1280, 'height': 720},
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        )
        page = await context.new_page()
        
        try:
            print("[1/5] Opening YouTube...")
            await page.goto('https://www.youtube.com', wait_until='networkidle')
            
            # Check if already logged in
            try:
                await page.wait_for_selector('a[aria-label="Create"]', timeout=5000)
                print("[2/5] Already logged in!")
            except:
                print("[2/5] Not logged in, signing in...")
                
                # Click sign in
                try:
                    await page.click('text=Sign in')
                except:
                    await page.click('a[href*="accounts.google.com"]')
                
                await page.wait_for_load_state('networkidle')
                await page.wait_for_timeout(1000)
                
                # Enter email
                print("[3/5] Entering email...")
                email_selector = 'input[type="email"]'
                await page.fill(email_selector, email)
                await page.press(email_selector, 'Enter')
                await page.wait_for_timeout(2000)
                
                # Enter password
                print("[4/5] Entering password...")
                password_selector = 'input[type="password"]'
                await page.fill(password_selector, password)
                await page.press(password_selector, 'Enter')
                
                # Wait for redirect
                print("Waiting for authentication...")
                try:
                    await page.wait_for_url('**/youtube.com/**', timeout=15000)
                    await page.wait_for_load_state('networkidle')
                except:
                    print("WARNING: May need 2FA or longer wait...")
                    await page.wait_for_timeout(5000)
            
            # Extract cookies
            print("[5/5] Extracting cookies...")
            cookies = await context.cookies()
            
            if not cookies:
                print("ERROR: No cookies found!")
                return False
            
            # Convert to Netscape format
            netscape_cookies = convert_to_netscape_format(cookies)
            
            # Save to file
            with open('youtube_cookies_new.txt', 'w') as f:
                f.write(netscape_cookies)
            
            print(f"SUCCESS! Extracted {len(cookies)} cookies")
            return True
        
        except Exception as e:
            print(f"ERROR: {e}")
            import traceback
            traceback.print_exc()
            return False
        finally:
            await browser.close()


def convert_to_netscape_format(cookies):
    """Convert Playwright cookies to Netscape format for yt-dlp"""
    lines = [
        '# Netscape HTTP Cookie File',
        '# Generated by auto_refresh_cookies workflow',
        ''
    ]
    
    for cookie in cookies:
        # Skip session cookies without expiry
        if not cookie.get('expires'):
            continue
        
        # Netscape format: domain\tflag\tpath\tsecure\texpiry\tname\tvalue
        parts = [
            cookie.get('domain', ''),
            'TRUE' if cookie.get('domain', '').startswith('.') else 'FALSE',
            cookie.get('path', '/'),
            'TRUE' if cookie.get('secure', False) else 'FALSE',
            str(int(cookie.get('expires', 0))),
            cookie.get('name', ''),
            cookie.get('value', '')
        ]
        line = '\t'.join(parts)
        lines.append(line)
    
    return '\n'.join(lines)


if __name__ == '__main__':
    result = asyncio.run(refresh_youtube_cookies())
    sys.exit(0 if result else 1)
